### ISSUE TITLE
Support for referencing Swagger definitions from private repositories

### ISSUE THREAD

**Issue by banshee86vr** [krateoplatformops/oasgen-provider#32]
### **Is your feature request related to a problem? Please describe.**
Currently, it seems that the `oasgen-provider` does not support referencing Swagger definitions hosted in private repositories (please confirm if this is correct). This limitation prevents users from securely fetching API definitions that are not publicly accessible. As a result, there is no built-in way to use authentication credentials, which makes working with private APIs more cumbersome and potentially insecure.

### **Describe the solution you'd like**
I would like the ability to reference a Swagger definition from a private repository. This could be implemented by allowing the specification of a Kubernetes Secret in the `RestDefinition` manifest to manage authentication credentials (e.g., personal access tokens, SSH keys, or basic auth credentials). The `oasgen-provider` could then use these credentials to securely fetch the Swagger file.

Here is a proposed update to the `RestDefinition` manifest to include this functionality:

```yaml
apiVersion: oasgen.krateo.io/v1alpha1
kind: RestDefinition
metadata:
  name: private-api
spec:
  source:
    type: git
    url: https://github.com/your-org/your-private-repo
    branch: main
    path: /swagger.yaml
    secretRef: 
      name: git-auth-secret
  options:
    # Additional options for processing
```

### **Describe alternatives you've considered**
1. **Manually hosting the Swagger file:** This involves downloading the Swagger file and placing it in a public location, which is not a secure option for private APIs.
2. **Using a custom init container:** This approach requires configuring a container to fetch the Swagger file during deployment, which adds complexity and maintenance overhead.

### **Additional context**
- The `secretRef` field in the manifest would reference a Kubernetes Secret containing authentication details such as a `username` and `password` (for basic auth) or a `token` (for personal access token-based authentication).
- This feature would enhance security and usability when working with private repositories and align with best practices for managing credentials in Kubernetes.
