### ISSUE TITLE
Local OpenAPI specification for Operator Generator

### ISSUE THREAD

**Issue by matteogastaldello** [krateoplatformops/oasgen-provider#34]
### Discussed in https://github.com/krateoplatformops/roadmap/discussions/71

<div type='discussions-op-text'>

<sup>Originally posted by **matteogastaldello** November 20, 2024</sup>
# Improving Local OpenAPI Specification Handling Between `oasgen-provider` and `rest-dynamic-controller`

## Current Situation

The `oasgen-provider` can handle local OpenAPI specifications through files mounted on its pod (typically via ConfigMaps). However, this creates a disconnect: the `rest-dynamic-controller` deployments generated from these specifications cannot access the same local OpenAPI files that were mounted on the `oasgen-provider` pod.

## Problem Details

1. Local OpenAPI specs are mounted only on `oasgen-provider` pod
2. Generated `rest-dynamic-controller` deployments need access to these specs
3. No current mechanism to share local specs between the two components
4. Mounting specs requires manual helm release modifications

## Current Flow
```mermaid
sequenceDiagram
    participant User
    participant ConfigMap
    participant oasgen-provider
    participant rest-dynamic-controller
    
    User->>ConfigMap: Creates with OpenAPI spec
    ConfigMap->>oasgen-provider: Mounts spec file
    oasgen-provider->>rest-dynamic-controller: Generates deployment
    rest-dynamic-controller--xConfigMap: Cannot access local spec
```

### Solution 1: Extend Current Mounting Approach

Extend the solution proposed in [discussion #68](https://github.com/krateoplatformops/roadmap/discussions/68) to handle local specifications.

#### Pros
- Consistent with existing approach
- Clear file structure
- Direct file access

#### Cons
- Requires helm release modification for each new local specification
- More maintenance overhead
- Less flexible for dynamic updates

#### Implementation
```yaml
# values.yaml modification required for each new spec
oasgenProvider:
  localSpecs:
    - name: spec1
      mountPath: /specs/spec1.yaml
      configMap: spec1-config
    - name: spec2
      mountPath: /specs/spec2.yaml
      configMap: spec2-config
```

### Solution 2: ConfigMap Reference in spec.oasPath

Allow `spec.oasPath` to reference a ConfigMap containing the specification directly.

#### Pros
- No helm release modifications needed
- More flexible and dynamic
- Easier maintenance
- Better separation of concerns
- Follows Kubernetes native patterns

#### Cons
- Requires implementation of ConfigMap reference handling
- Could requires the modification of the RestDefinition CRD (breaking change?) to handle also Configmap references or a solution as the one proposed below

#### Implementation Example

```yaml
apiVersion: core.krateo.io/v1alpha1
kind: OASDefinition
metadata:
  name: my-api
spec:
  # Reference format: configmap://<namespace>/<configmap-name>/<key>
  oasPath: configmap://default/my-api-spec/openapi.yaml
```

## Recommendation

**Solution 2 (ConfigMap Reference)** is recommended because:
1. More flexible and maintainable
2. No need to modify helm releases
3. Follows Kubernetes patterns
4. Better separation of concerns
5. Easier to automate and manage programmatically</div>
