### ISSUE TITLE
Unhandled Error with Custom ResourceDefinition from RestDefinition: failed to list *unstructured.Unstructured

### ISSUE THREAD

**Issue by banshee86vr** [krateoplatformops/oasgen-provider#35]
### **Describe the bug**
After generating an operator and CRD using the `RestDefinition` manifest below, the operator fails with the following error before attempting to create any CustomResource (CR):

```
E1120 14:05:06.201605       1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource" logger="UnhandledError"
```

The error suggests that the operator cannot find the requested resource on the Kubernetes API server.

---

### **RestDefinition Manifest**
This is the manifest used to generate the operator:

```yaml
kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: github-runnergroup
  namespace: gh-runners
spec:
  oasPath: https://raw.githubusercontent.com/banshee86vr/github-runner-group-swagger/refs/heads/main/ghec_extracted.yaml
  resourceGroup: github.customer.com
  resource:
    kind: RunnerGroup
    identifiers:
      - org
      - runner_group_id
    verbsDescription:
      - action: findby
        method: GET
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
      - action: get
        method: GET
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
      - action: update
        method: PATCH
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
      - action: create
        method: POST
        path: /orgs/{org}/actions/runner-groups
      - action: delete
        method: DELETE
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
```

The Swagger file used in this manifest can be found [here](https://raw.githubusercontent.com/banshee86vr/github-runner-group-swagger/refs/heads/main/ghec_extracted.yaml).

---

### **To Reproduce**
1. Apply the `RestDefinition` manifest shown above to a Kubernetes cluster.
2. Wait for the operator and CRD to be generated.
3. Deploy the operator to the cluster.
4. Check the operator logs.

---

### **Expected behavior**
The operator should reconcile the CRD and process CustomResources (CRs) as defined in the `RestDefinition` manifest without errors.

---

### **Operator Logs**
Error observed in the operator logs:
```
E1120 14:05:06.201605       1 reflector.go:158] "Unhandled Error" err="pkg/mod/k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource" logger="UnhandledError"
```

---

### **Generated CRD Manifest**
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: runnergroups.github.customer.com
spec:
  group: github.customer.com
  names:
    kind: RunnerGroup
    plural: runnergroups
    singular: runnergroup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          spec:
            properties:
              allows_public_repositories:
                type: boolean
              name:
                type: string
              org:
                type: string
              page:
                type: integer
              per_page:
                type: integer
              restricted_to_workflows:
                type: boolean
              runner_group_id:
                type: integer
              runners:
                type: array
                items:
                  type: integer
              selected_repository_ids:
                type: array
                items:
                  type: integer
              selected_workflows:
                type: array
                items:
                  type: string
              visibility:
                type: string
                enum:
                - selected
                - all
                - private
              visible_to_repository:
                type: string
            required:
            - name
          status:
            properties:
              org:
                type: string
              runner_group_id:
                type: string
    served: true
    storage: true
```

---

### **Additional context**
- The `RestDefinition` manifest appears correctly applied, and the CRD is created without conflicts.
