### ISSUE TITLE
Reconciliation Loop and Deletion Failure for RunnerGroup

### ISSUE THREAD

**Issue by bertellil-prom** [krateoplatformops/oasgen-provider#41]
**Describe the bug**  
The `RunnerGroup` resource is successfully created on GitHub using the provided `RestDefinition` and manifest. However:  
1. Subsequent reconciliation attempts continuously try to recreate the resource, resulting in a `409 Conflict` error because the runner group already exists.  
2. Deletion of the `RunnerGroup` custom resource fails with a `404 Not Found` error, indicating that the runner group does not exist.  
3. The field `spec.runner_group_id` is currently required during the creation of the resource, despite the API not requiring it. The `runner_group_id` should instead be part of the creation response and automatically populated into the `status` or `spec`.

**Error Logs**  
During reconciliation:  
```log
2024-11-28T15:33:48Z    DEBUG   rest-dynamic-controller External resource not found     {"op": "Observe", "apiVersion": "github.customer.com/v1alpha1", "kind": "RunnerGroup", "name": "runner-test", "namespace": "gh-runners"}
2024-11-28T15:33:49Z    DEBUG   rest-dynamic-controller Creating external resource      {"op": "Create", "apiVersion": "github.customer.com/v1alpha1", "kind": "RunnerGroup", "name": "runner-test", "namespace": "gh-runners", "error": "unexpected status: 409: error: Already exists - Runner group runner-test-by-crd already exists. (, 0)"}
```

During deletion:  
```log
2024-11-28T15:35:06Z    DEBUG   rest-dynamic-controller Performing REST call    {"op": "Delete", "apiVersion": "github.customer.com/v1alpha1", "kind": "RunnerGroup", "name": "runner-test", "namespace": "gh-runners", "error": "unexpected status: 404: error: Runner group does not exist. (, 0)"}
2024-11-28T15:35:06Z    DEBUG   rest-dynamic-controller DeleteFunc: deleting object     {"error": "unexpected status: 404: error: Runner group does not exist. (, 0)"}
```

**To Reproduce**  
1. Apply the provided `RestDefinition` and `RunnerGroup` manifest to create a runner group on GitHub.  
2. Observe the controller logs for repeated reconciliation attempts that try to recreate the existing runner group.  
3. Attempt to delete the `RunnerGroup` custom resource and observe the failure in the logs.  

**Expected behavior**  
- Reconciliation should correctly detect that the runner group already exists and skip the creation step unless there is a difference between the current and desired state.  
- Deletion should gracefully remove the `RunnerGroup` resource without encountering a `404 Not Found` error.  
- During creation, the `runner_group_id` field should not be required in the `spec`. Instead, it should be automatically populated in the `status` (or `spec`) as part of the API creation response.

**Additional context**  
- The issue during reconciliation suggests that the `Observe` operation is not correctly identifying the existing runner group.  
- The deletion issue may indicate a mismatch in the identifier used to locate the runner group on GitHub.  
- The requirement of `spec.runner_group_id` during creation contradicts the expected behavior of the API, which generates the ID as part of the resource creation process. This ID should be captured and stored in the resource automatically. 

**RestDefinition**  
```yaml
kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: github-runnergroup
  namespace: gh-runners
spec:
  oasPath: https://raw.githubusercontent.com/banshee86vr/github-runner-group-swagger/refs/heads/main/ghec_extracted.yaml
  resourceGroup: github.customer.com
  resource:
    kind: RunnerGroup
    identifiers:
      - org
      - runner_group_id
    verbsDescription:
      - action: findby
        method: GET
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
      - action: get
        method: GET
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
      - action: update
        method: PATCH
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
      - action: create
        method: POST
        path: /orgs/{org}/actions/runner-groups
      - action: delete
        method: DELETE
        path: /orgs/{org}/actions/runner-groups/{runner_group_id}
```

**RunnerGroup Manifest**  
```yaml
apiVersion: github.customer.com/v1alpha1
kind: RunnerGroup
metadata:
  name: runner-test
  namespace: gh-runners
spec:
  runner_group_id: 123
  allows_public_repositories: false
  name: runner-test-by-crd
  org: prom-candp
  selected_repository_ids:
    - 123123123
  visibility: private
  authenticationRefs:
    bearerAuthRef: bearer-gh-ref
```
